import { Button }  from "std-widgets.slint";

MainWindow := Window {
    width: 480px;
    height: 320px;

    property thermo_image <=> thermo_image.source;
    property scale_image <=> scale_image.source;
    
    property max_temp_text <=> max_temp_text.text;
    property mean_temp_text <=> mean_temp_text.text;
    property min_temp_text <=> min_temp_text.text;

    property lower_scale_temp_text <=> lower_scale_temp_text.text;
    property upper_scale_temp_text <=> upper_scale_temp_text.text;
    
    callback autoscale-toggled(bool);
    callback manual-scale-max-temp-increased();
    callback manual-scale-max-temp-decreased();
    callback manual-scale-min-temp-increased();
    callback manual-scale-min-temp-decreased();

    HorizontalLayout {
        VerticalLayout { 
            HorizontalLayout { 
                thermo_image := Image {
                    padding-left: 5px;
                }  // expected size: 256x192
                VerticalLayout { 
                    lower_scale_temp_text := Text {
                        vertical-alignment: TextVerticalAlignment.center;
                        horizontal-alignment: TextHorizontalAlignment.center;
                    }
                    scale_image := Image{}
                    upper_scale_temp_text := Text {
                        vertical-alignment: TextVerticalAlignment.center;
                        horizontal-alignment: TextHorizontalAlignment.center;
                    }
                }
            }
            Rectangle { 
                x: 5px;
                width: 310px;
                height: 1px;
                background: black;

            }
            HorizontalLayout { 
                min_temp_text := Text {
                    vertical-alignment: TextVerticalAlignment.center;
                    horizontal-alignment: TextHorizontalAlignment.center;
                }
                mean_temp_text := Text {
                    vertical-alignment: TextVerticalAlignment.center;
                    horizontal-alignment: TextHorizontalAlignment.center;
                }
                max_temp_text := Text {
                    vertical-alignment: TextVerticalAlignment.center;
                    horizontal-alignment: TextHorizontalAlignment.center;
                }
            }
        }
        VerticalLayout { 
            autoscale_button := Button { 
                text: "Autoscale";
                checked: true;
                checkable: true;
                clicked => { autoscale-toggled(self.checked) }
            }
            HorizontalLayout {
                Button {
                    enabled: !autoscale_button.checked;
                    text: "Min -";
                    clicked => { manual-scale-min-temp-decreased() }
                }
                Button {
                    enabled: !autoscale_button.checked;
                    text: "Min +";
                    clicked => { manual-scale-min-temp-increased() }
                }                
            }
            HorizontalLayout { 
                Button { 
                    enabled: !autoscale_button.checked;
                    text: "Max -";
                    clicked => { manual-scale-max-temp-decreased() }
                }   
                Button { 
                    enabled: !autoscale_button.checked;
                    text: "Max +";
                    clicked => { manual-scale-max-temp-increased() }
                }                
            }
        }
    }
}